[build]
  base = "exampleSite/"
  publish = "public/"
  command = "mkdir -p themes && rsync -Rr /opt/build/repo ./themes/hugo-theme-vanity && ls -la ./themes && ls -la ./themes/hugo-theme-vanity && hugo"