[build]
  base = "exampleSite/"
  publish = "public/"
  command = "echo 'Using exampleSite/netlify.toml' && git submodule add https://github.com/markdumay/hugo-theme-vanity.git themes/hugo-theme-vanity && hugo"